Redux
DanisHaertdinov/six-cities pull request #10
Opened 2021-02-04 21:40 UTC by DanisHaertdinov

2021-02-14 10:20 UTC, kicumkicum requested changes
Ништяк 👍🏽 👍🏽 👍🏽

2021-02-14 10:20 UTC, kicumkicum commented on src/components/app/app-container.jsx
> +import {getAuthorizationStatus} from "../../store/user/selectors";
Порекомендую использовать суффиксы через точку `app.container.jsx`, `app.spec.js`,  `auth-page.container.jsx`, `app.stateless.jsx`, `app.statefull.jsx`. Последние два просто для примера того, что в проекте можно определить некий набор суффиксов, которые легко отличать визуально от основного имени компонента

2021-02-14 10:20 UTC, kicumkicum commented on src/components/app/app-container.jsx
> +import {getAuthorizationStatus} from "../../store/user/selectors";
Именуй селекторы, начиная с `select`, а не `get`. Общепринято, типа

2021-02-14 10:20 UTC, kicumkicum commented on src/components/app/app.jsx
> +            </LoginPage>}
FYI Могу предложить вот такой стиль. Но это не обязательно

```suggestion
          {
             isUserAuthorized
               ? <Redirect
                    to={`/`}
                  />
               : <LoginPage>
                  <Header/>
                  <LoginForm/>
                  <Location/>
                </LoginPage>
          }
```

2021-02-14 10:20 UTC, kicumkicum commented on src/components/login-page/login-page-container.jsx
> +const mapDispatchToProps = {onSubmit: authorize};
А куда `dispatch` мапится? Тут точно все верно?

2021-02-14 10:20 UTC, kicumkicum commented on src/components/login-page/login-page-container.jsx
> +const mapDispatchToProps = {onSubmit: authorize};
И прям работает?

2021-02-14 10:20 UTC, kicumkicum commented on src/components/login-page/login-page.jsx
> +  const [password, setPassword] = useState(``);
Это называется управляемые компоненты - когда мы сохраняем значение инпутов в стейт и перерендериваем их. Но это верный путь к падению производительности, потому что часто вызывается render-функция (на каждое нажатие кнопки клавиатуры). Лучше стараться обойтись без стейта для решения этой задачи. Или объяснить, почему это невозможно

2021-02-14 10:20 UTC, kicumkicum commented on src/index.js
> +import {configureStore} from '@reduxjs/toolkit';
Одинарная кавыча или двойная?)) Определи в editorconfig или в линтер. Но лучше в editorconfig. Потому что универсальнее

2021-02-14 10:20 UTC, kicumkicum commented on src/store/reducer.js
> +  user: userReducer,
Че, может `user` в константы сразу?

2021-02-14 10:20 UTC, kicumkicum commented on src/util/test-helpers.js
> +const renderWithRouter = (ui, {route = `/`} = {}) => {
Если `ui` это компонент, то лучше так и назвать

2021-02-14 12:41 UTC, DanisHaertdinov commented on src/components/login-page/login-page-container.jsx
> +const mapDispatchToProps = {onSubmit: authorize};
хм, в доке redux-toolkit, mapDispatchToProps использовался именно так, хотя я видел, что многие используют по другому . Работает, да. Пойду читать доку

2021-02-14 13:14 UTC, DanisHaertdinov commented on src/components/login-page/login-page-container.jsx
> +const mapDispatchToProps = {onSubmit: authorize};
mapDispatchToProps насколько я понял из документации можно использовать в двух формах в виде функции и в виде объекта во втором случае dispatch не требуется и redux автоматический вызовет bindActionCreators, в документации рекомендуется использовать именно вторую форму, кроме особых случаев(ownProps, цепочка вызовов и т.п.).
https://react-redux.js.org/using-react-redux/connect-mapdispatch#defining-mapdispatchtoprops-as-an-object

2021-02-15 06:25 UTC, DanisHaertdinov commented on src/components/app/app-container.jsx
> +import {getAuthorizationStatus} from "../../store/user/selectors";
done

2021-02-15 06:25 UTC, DanisHaertdinov commented on src/components/app/app-container.jsx
> +import {getAuthorizationStatus} from "../../store/user/selectors";
done

2021-02-15 06:25 UTC, DanisHaertdinov commented on src/index.js
> +import {configureStore} from '@reduxjs/toolkit';
done

2021-02-15 06:25 UTC, DanisHaertdinov commented on src/store/reducer.js
> +  user: userReducer,
done

2021-02-15 06:25 UTC, DanisHaertdinov commented on src/util/test-helpers.js
> +const renderWithRouter = (ui, {route = `/`} = {}) => {
done

2021-02-15 12:03 UTC, kicumkicum approved these changes

2021-02-15 12:04 UTC, kicumkicum commented
Нужно порезолвить конфликты и можно нажимать кнопку мерж

2021-02-15 12:26 UTC, merged