Typescript
DanisHaertdinov/six-cities pull request #11
Opened 2021-03-07 02:03 UTC by DanisHaertdinov

2021-03-07 17:42 UTC, kicumkicum commented on .gitignore
> +/dist
Слеш вначале не нужен,

2021-03-07 18:19 UTC, kicumkicum requested changes
Всё круто. Посмотрел почти всё. Осталось несколько файлов. С ними наверное завтра справлюсь

2021-03-07 18:19 UTC, kicumkicum commented on src/components/app/app.container.tsx
> +import {RootState} from "../../store/reducer";
Кавычки)

2021-03-07 18:19 UTC, kicumkicum commented on package.json
>      "start": "webpack-dev-server",
А почему скрипт тест не запускает тесты?

2021-03-07 18:19 UTC, kicumkicum commented on src/components/app/app.tsx
> +          {/* </OfferPage>*/}
Эти комменты нужны?

2021-03-07 18:19 UTC, kicumkicum commented on src/components/offer-page/offer-page.tsx
> +}
Если тут опционально, то на 15ой будет ексепшен

2021-03-08 16:03 UTC, DanisHaertdinov commented on .gitignore
> +/dist
done

2021-03-08 16:04 UTC, DanisHaertdinov commented on src/components/app/app.container.tsx
> +import {RootState} from "../../store/reducer";
done

2021-03-08 16:06 UTC, DanisHaertdinov commented on package.json
>      "start": "webpack-dev-server",
Так было во всех проектах академии, что скрипт test запускал eslint. Думаешь лучше перенести в test тесты jest?

2021-03-08 16:08 UTC, DanisHaertdinov commented on src/components/app/app.tsx
> +          {/* </OfferPage>*/}
Временные комменты уберу их со временем, пока пусть будут.

2021-03-08 16:11 UTC, DanisHaertdinov commented on src/components/offer-page/offer-page.tsx
> +}
Тоже временно добавил, чтобы при сборке, ничего не ломалось, знаю как исправить, просто не хочу в этой ветке делать ничего что не связанно с typescript

2021-03-08 18:06 UTC, kicumkicum commented on src/components/offer-page/offer-page.tsx
> +}
Можно добавить тудушку

```js
// TODO: Some text
```

2021-03-08 18:07 UTC, kicumkicum commented on src/components/app/app.tsx
> +          {/* </OfferPage>*/}
Тоже можно добавить тудушку

2021-03-08 18:12 UTC, kicumkicum commented on package.json
>      "start": "webpack-dev-server",
Да, лучше перенести

2021-03-09 07:30 UTC, DanisHaertdinov commented on src/components/app/app.tsx
> +          {/* </OfferPage>*/}
done

2021-03-09 07:30 UTC, DanisHaertdinov commented on src/components/offer-page/offer-page.tsx
> +}
done

2021-03-09 07:30 UTC, DanisHaertdinov commented on package.json
>      "start": "webpack-dev-server",
done

2021-03-15 17:44 UTC, kicumkicum approved these changes

2021-03-15 17:44 UTC, merged