Common components
DanisHaertdinov/six-cities pull request #13
Opened 2021-03-22 02:27 UTC by DanisHaertdinov

2021-03-22 18:50 UTC, kicumkicum requested changes
Все отлично 👍🏽

2021-03-22 18:50 UTC, kicumkicum commented on src/components/favorite-mark/favorite-mark.spec.tsx
> +import userEvent from '@testing-library/user-event';
FYI Может добавить сортировку импортов в линтер по их пути?

2021-03-22 18:50 UTC, kicumkicum commented on src/components/favorite-mark/favorite-mark.spec.tsx
> +          onClick={jest.fn()}
На самом деле передавать `jest.fn()` без сохранения в переменную особого смысла нет. Ведь ты не можешь ничего проверить. Можно использовать пустую стрелочную функцию или сохранить ее в переменной `noop` и использовать ее

2021-03-22 18:50 UTC, kicumkicum commented on src/components/favorite-mark/favorite-mark.spec.tsx
> +    const favoriteButton = screen.getByRole(`button`, {name: /In bookmarks/i});
В этой паре кейсов можно проверить, что тут линк не находится. А в кейсе выше не находится баттон. А то если придти в компонент, удалиить тернарник и рендерить и то, и другое сразу, то тесты не упадут. Но компонент будет сломан.

2021-03-22 18:50 UTC, kicumkicum commented on src/components/page-wrapper/page-wrapper.tsx
> +      data-testid={`page-wrapper`}
Строки отстой. Помести это в константу и импорти из компонента в тестах

2021-03-22 18:50 UTC, kicumkicum commented on src/components/page-wrapper/page-wrapper.spec.tsx
> +        </PageWrapper>);
Как-то уж стиль совсем уехал)

2021-03-22 18:50 UTC, kicumkicum commented on src/components/page-wrapper/page-wrapper.tsx
> +const DEFAULT_CLASS_NAMES = `page`;
Лучше сначала константы, а потом интерфейсы и типы. Потому что константы однострочные и их можно быстренько прочитать и еще и типы захватить

2021-03-28 17:18 UTC, DanisHaertdinov commented on src/components/favorite-mark/favorite-mark.spec.tsx
> +import userEvent from '@testing-library/user-event';
done

2021-03-28 17:18 UTC, DanisHaertdinov commented on src/components/favorite-mark/favorite-mark.spec.tsx
> +          onClick={jest.fn()}
done

2021-03-28 17:18 UTC, DanisHaertdinov commented on src/components/favorite-mark/favorite-mark.spec.tsx
> +    const favoriteButton = screen.getByRole(`button`, {name: /In bookmarks/i});
done

2021-03-28 17:19 UTC, DanisHaertdinov commented on src/components/page-wrapper/page-wrapper.tsx
> +      data-testid={`page-wrapper`}
done

2021-03-28 17:19 UTC, DanisHaertdinov commented on src/components/page-wrapper/page-wrapper.spec.tsx
> +        </PageWrapper>);
done

2021-03-28 17:19 UTC, DanisHaertdinov commented on src/components/page-wrapper/page-wrapper.tsx
> +const DEFAULT_CLASS_NAMES = `page`;
done

2021-03-29 17:11 UTC, kicumkicum approved these changes

2021-03-29 17:12 UTC, kicumkicum approved these changes
Все офигенно!

2021-03-29 17:12 UTC, merged