Components
DanisHaertdinov/six-cities pull request #4
Opened 2021-01-16 18:57 UTC by DanisHaertdinov

2021-01-16 20:12 UTC, kicumkicum requested changes
Крутяг! Правда я еще не запускал, но сделаю еще позже)

Есть еще несколько проблем, касаемо хорошего/красивого кода, но я о них не написал. Тебе нужно найти их и устранить))

2021-01-16 20:12 UTC, kicumkicum commented on src/components/login-page/login-page.spec.js
> +  it(`Submit button: should be disabled if email is not valid or password input is empty`, () => {
Разбей лучше на два кейса. Потому что когда у тебя OR, то разработчику нужно в голове держать два условия сразу. Это сложно.

А в реализации ты можешь получить в первом кейсе сайдеффекты для второго кейса.

Ну и меньше текста, меньше кода, меньше ветвлений - проще понимать и запоминать

2021-01-16 20:12 UTC, kicumkicum commented on src/components/login-page/login-page.spec.js
> +    expect(submitButton).not.toBeDisabled();
`expect` он как `return` - лучше отбивать пустой строкой

2021-01-16 20:12 UTC, kicumkicum commented on src/components/login-page/login-page.spec.js
> +  it(`Submit button: should be active if email is valid and password input not empty`, () => {
У тебя получилось несколько кейсов с префиксом `Submit button:`. Создай из этого тестовый набор

2021-01-16 20:12 UTC, kicumkicum commented on src/components/login-page/login-page.spec.js
> +    const {inputLogin, inputPassword, submitButton} = setup();
Сейчас может немного сложно, но попроси меня в понедельник тебе рассказать подробнее. В программировании ты привык, что дублирование зло. Об этом все говорят и это правда. Но написание тестов это программирование немного под другим углом. Иногда говорят, что тесты - это код с душком. Так вот, получение ссылки на элементы или данный создавать заново и ближе к месту использования.
Ближе - чтобы проще читать. Тесты это много тест-кейсов и когда все можно прочитать не скроля и не кликая - очень хорошо.
Дублируя код - чтобы одна функция не аффектила много тест-кейсов. Типа, вот у тебя функция, и она используется в десятке тест-кейсов. Ты ее сломал и у тебя много красноты. Станет немного не по себе и не упростит фиксинг. Это немного размытое утверждение и может даже спорное. `render` можно оставить в функции, потому что он все равно подразумевается. А получение данных лучше в каждый тест-кейс перенести

2021-01-18 12:59 UTC, DanisHaertdinov commented on src/components/login-page/login-page.spec.js
> +    const {inputLogin, inputPassword, submitButton} = setup();
done

2021-01-18 12:59 UTC, DanisHaertdinov commented on src/components/login-page/login-page.spec.js
> +  it(`Submit button: should be active if email is valid and password input not empty`, () => {
done

2021-01-18 12:59 UTC, DanisHaertdinov commented on src/components/login-page/login-page.spec.js
> +    expect(submitButton).not.toBeDisabled();
done

2021-01-18 12:59 UTC, DanisHaertdinov commented on src/components/login-page/login-page.spec.js
> +  it(`Submit button: should be disabled if email is not valid or password input is empty`, () => {
done

2021-01-18 16:59 UTC, kicumkicum commented on src/components/login-page/login-page.spec.js
> +describe(`submit button`, () => {
Этот набор стоит вложить в `login-page`

2021-01-18 17:20 UTC, kicumkicum approved these changes
👍🏽

2021-01-25 16:38 UTC, merged